### ISSUE TITLE
Delegate has been deprecated

### ISSUE THREAD

**Issue by Arevico** [cballou/jQuery-Form-Element-Repeater-Plugin#11]
http://api.jquery.com/delegate/
As of jQuery 3.0, .delegate() has been deprecated. It was superseded by the .on() method since jQuery 1.7, so its use was already discouraged. For earlier versions, however, it remains the most effective means to use event delegation. More information on event binding and delegation is in the .on() method. In general, these are the equivalent templates for the two methods:_

Please change with .on

**Comment by cballou** [comment]
Resolved in https://github.com/cballou/jQuery-Form-Element-Repeater-Plugin/commit/8e10cab0516427cac6ec6f545e71f37dd730b619
